overrides:
  '@angular/router': 22.1.3
  '@angular/platform-server': 22.1.3
  '@angular/platform-browser-dynamic': 22.1.3
  '@angular/platform-browser': 22.1.3
  '@angular/forms': 22.1.3
  '@angular/core': 22.1.3
  '@angular/compiler': 22.1.3
  '@angular/common': 22.1.3
  '@angular/animations': 22.1.3
packages:
  - 'libs/**'
peerDependencyRules:
  ignoreMissing:
    - '@sneat/*'
    - '@ionic/angular'
    - firebase
    - '@angular/fire'
    - '@sentry/angular'
    - posthog-js
    - '@sneat/random'
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - less
  - lmdb
  - msgpackr-extract
  - nx
  - oxc-resolver
  - unrs-resolver
